version: '3'
services:
  zookeeper:
    image: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - ./data/zookeeper:/data
      - ./logs/zookeeper:/logs
#    networks:
#      simplifiedtech-network:
  kafka:
    image: wurstmeister/kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
#    ports:
#      - "9092:9092"
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_NUM_PARTITIONS: 3
#      KAFKA_LOG_DIRS: /kafka/logs
#      KAFKA_HEAP_OPTS: "-Xmx1g -Xms1g"
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#      KAFKA_CREATE_TOPICS: "topic1:1:1"
    volumes:
      - ./data/kafka:/kafka/data
      - ./logs/kafka:/kafka/
#    networks:
#      simplifiedtech-network:

#networks:
#  simplifiedtech-network: