version: "3"
services:
  zookeeper:
    image: 'wurstmeister/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    volumes:
      - ./data/zookeeper:/data
      - ./logs/zookeeper:/logs
  kafka:
    image: 'wurstmeister/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_LOG_DIRS=/kafka/logs
      - KAFKA_HEAP_OPTS=-Xmx1g -Xms1g
      - KAFKA_CREATE_TOPICS=topic1:1:1,tebatso:1:1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    volumes:
      - ./data/kafka:/kafka/data
      - ./logs/kafka:/kafka/